
import React from "react";
import { Button } from "@/components/ui/button";
import { FileDown } from "lucide-react";
import { Tenant } from "@/types";
import { toast } from "sonner";

interface TenantsPdfReportProps {
  tenants: Tenant[];
}

export function TenantsPdfReport({ tenants }: TenantsPdfReportProps) {
  const generatePDF = () => {
    try {
      // Create a new window for printing
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast.error("Please allow popups to generate PDF");
        return;
      }

      // Generate HTML content for the PDF
      const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Tenants Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              margin: 20px;
              font-size: 12px;
            }
            h1 {
              color: #333;
              text-align: center;
              margin-bottom: 30px;
            }
            table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 20px;
            }
            th, td {
              border: 1px solid #ddd;
              padding: 8px;
              text-align: left;
            }
            th {
              background-color: #f2f2f2;
              font-weight: bold;
            }
            .status {
              padding: 2px 6px;
              border-radius: 3px;
              font-size: 10px;
              font-weight: bold;
            }
            .status-active { background-color: #d4edda; color: #155724; }
            .status-late { background-color: #f8d7da; color: #721c24; }
            .status-notice { background-color: #fff3cd; color: #856404; }
            .status-inactive { background-color: #e2e3e5; color: #383d41; }
            .footer {
              margin-top: 30px;
              text-align: center;
              font-size: 10px;
              color: #666;
            }
          </style>
        </head>
        <body>
          <h1>Tenants Report</h1>
          <p><strong>Generated on:</strong> ${new Date().toLocaleDateString()}</p>
          <p><strong>Total Tenants:</strong> ${tenants.length}</p>
          
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Unit</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Rent Amount</th>
                <th>Move In Date</th>
                <th>Lease End Date</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${tenants.map(tenant => `
                <tr>
                  <td>${tenant.name}</td>
                  <td>${tenant.unit}</td>
                  <td>${tenant.email}</td>
                  <td>${tenant.phone || 'N/A'}</td>
                  <td>$${tenant.rentAmount.toFixed(2)}</td>
                  <td>${new Date(tenant.moveInDate).toLocaleDateString()}</td>
                  <td>${tenant.leaseEndDate ? new Date(tenant.leaseEndDate).toLocaleDateString() : 'No End Date'}</td>
                  <td><span class="status status-${tenant.status}">${tenant.status.toUpperCase()}</span></td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          
          <div class="footer">
            <p>This report was generated by RentFlow Property Management System</p>
          </div>
        </body>
        </html>
      `;

      // Write content to the new window
      printWindow.document.write(htmlContent);
      printWindow.document.close();

      // Wait a moment then trigger print
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);

      toast.success("PDF report generated successfully");
    } catch (error) {
      console.error("Error generating PDF:", error);
      toast.error("Error generating PDF report");
    }
  };

  return (
    <Button onClick={generatePDF} className="gap-2">
      <FileDown className="h-4 w-4" />
      Export Tenants PDF
    </Button>
  );
}
