// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhscuftwypziepjgnfan.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoc2N1ZnR3eXB6aWVwamduZmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTAxMjIsImV4cCI6MjA2Mzc2NjEyMn0.OD4IzuutB5D_Bz6BLeVgxLcpq0UjlVDQMWTXPnq-on8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);